# Generated by Django 2.1.7 on 2019-03-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_Gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Name',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
    ]
